// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonelProjesiDataAccess;

#nullable disable

namespace PersonelProjesiDataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonelProjesiDomain.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsZimmet")
                        .HasColumnType("bit");

                    b.Property<int>("Maas")
                        .HasColumnType("int");

                    b.Property<string>("Mezuniyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Personels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adi = "Ahmet",
                            Cinsiyet = "Erkek",
                            Departman = "Yazılım",
                            DogumTarihi = new DateTime(1990, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsZimmet = true,
                            Maas = 50000,
                            Mezuniyet = "İstanbul Üniversitesi",
                            Sehir = "İstanbul",
                            Soyadi = "Yılmaz"
                        },
                        new
                        {
                            Id = 2,
                            Adi = "Ayşe",
                            Cinsiyet = "Kadın",
                            Departman = "Pazarlama",
                            DogumTarihi = new DateTime(1999, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsZimmet = true,
                            Maas = 45000,
                            Mezuniyet = "Ankara Üniversitesi",
                            Sehir = "Ankara",
                            Soyadi = "Demir"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
